// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package test_ns

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MyData struct {
	_tab flatbuffers.Table
}

func GetRootAsMyData(buf []byte, offset flatbuffers.UOffsetT) *MyData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MyData{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsMyData(buf []byte, offset flatbuffers.UOffsetT) *MyData {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MyData{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *MyData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MyData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MyData) Value() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MyData) MutateValue(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func MyDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MyDataAddValue(builder *flatbuffers.Builder, value int32) {
	builder.PrependInt32Slot(0, value, 0)
}
func MyDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
