version: "3"

services: 
  redis:
    image: redis
    ports:
      - 6000:6379
    volumes: 
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ./conf/data:/data
    command: "redis-server /etc/redis/redis.conf"
    logging: 
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
